### PR TITLE
Join Team Form

### PR DESCRIPTION
**Pull request by BellCubeDev**
# What's this?
A fully-featured "Join Team" form for letting users add themselves to the SFCP team. Includes a team selector that pulls teams directly from the organization at build time.
<details><summary><h2>Screenshots</h2></summary>
    
image
image
image

</details>

BellCube, signing off.

### CODE REVIEW

**Comment by Noggog** [comment]
Nice!  Does the team list populate from the org?  Eg, show `QA` and `dev` at the moment?

Also, is there the ability to type in the github username as an alternative to the email?

**Comment by Pickysaurus** [comment]
What is the Octokit library being imported for? If it's just for one call maybe we can just write a query?

**Comment by BellCubeDev** [comment]
@Noggog The form pulls Team data directly from the organization when the site is built and displays them in a dropdown.

While the form could theoretically allow for a GitHub username (and I did think about doing this), that would allow someone to easily spam another user with invites. With the email method, you would have to know the person's email already and using the SFCP website as a proxy for email spam seems a little pointless. From a technical perspective, it would require an additional fetch request to find the user's numerical ID and shoot that off to the invite endpoint but I don't think that would be a huge issue.

@Pickysaurus I'm using the REST component of the library (Octokit is GitHub's official library). It's significantly safer than writing the requests by hand, especially if the API gets changed down the road. If the extra dependency is a problem, the REST query could be rewritten, but you do lose that end-to-end type safety. Note that Vercel doesn't have strict server size limits and Octokit is being used strictly server-side.

I'm using it both to fetch the teams and to tell GitHub to send the invite out, though I'd imagine the teams fetch could probably be integrated directly with some other query. Then again, though, that teams request is only fired off during build time.

Sadly, the invite endpoint doesn't seem to exist in the GraphQL API (I've looked a few times now).

**Review by Noggog — APPROVED** [review]
> that would allow someone to easily spam another user with invites
Ah, nice thinking!

Looks cool to me.  @Pickysaurus the final say, id say

**Review by Pickysaurus — APPROVED** [review]
Looks fine, thanks!

**Review by Pickysaurus — CHANGES_REQUESTED** [review]
Please include the `src/app/join-team/page.tsx` file, if you can find it!

**Comment by Pickysaurus** [comment]
Merged manually via https://github.com/Starfield-Community-Patch/Website/commit/3b3c3adc16108bd60876918d7ab8332ee2c26764

**Pull request closed without merging**
